### ISSUE TITLE
Failed to build on Ubuntu 25.04, linker error

### ISSUE THREAD

**Issue by raleighlittles** [haasn/libplacebo#326]
Trying to build this library so I can build the latest version of FFMPEG. Encountered a linker `ld` error during the step:

```bash
$ ninja -C$DIR
```

Error:

```
FAILED: demos/plplay
/usr/bin/ld: /usr/local/lib/libavcodec.a(libx265.o): in function `libx265_get_supported_config':
/home/raleigh/2025-01-05_ffmpeg/libavcodec/libx265.c:993:(.text+0x1a): undefined reference to `x265_api_get_209'
/usr/bin/ld: /home/raleigh/2025-01-05_ffmpeg/libavcodec/libx265.c:996:(.text+0x56): undefined reference to `x265_api_get_209'
/usr/bin/ld: /home/raleigh/2025-01-05_ffmpeg/libavcodec/libx265.c:999:(.text+0x7e): undefined reference to `x265_api_get_209'
/usr/bin/ld: /usr/local/lib/libavcodec.a(libx265.o): in function `libx265_encode_init':
/home/raleigh/2025-01-05_ffmpeg/libavcodec/libx265.c:261:(.text.unlikely+0x20d): undefined reference to `x265_api_get_209'
/usr/bin/ld: /home/raleigh/2025-01-05_ffmpeg/libavcodec/libx265.c:263:(.text.unlikely+0x21d): undefined reference to `x265_api_get_209'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

Before this I ran the meson step which finished successfully. This is the final output of the previous command:

```
libplacebo 7.351.0

  Optional features
    d3d11       : NO
    dovi        : YES
    gl-proc-addr: YES
    glslang     : NO
    lcms        : YES
    libdovi     : NO
    opengl      : YES
    shaderc     : YES
    vk-proc-addr: YES
    vulkan      : YES
    xxhash      : YES

Found ninja-1.12.1 at /usr/bin/ninja
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
```

I'm using this commit hash: `538c78dee2330039fed747120cb0620122f5c7e6`

This is my OS info

```
OS: Ubuntu 25.04
Kernel: 6.14.0-15-generic
```
